[package]
name = "chain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hash = "0.3.4"
hex = "0.4.3"
chrono = "0.4.19"
rand = "0.8.4"
wallet = { path = "../wallet" }
serde_json = "1.0.72"