[package]
name = "miner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chain = { path = "../chain" }
rand = "0.8.4"
tokio = { version = "1.13.0", features = ["full"] }
